[workspace]

members = [
    "modules",
    "relayer",
    "relayer-cli",
    "telemetry",
    "proto",
]

exclude = [
    "proto-compiler"
]

[patch.crates-io]
tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/prost-0.8" }
tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/prost-0.8" }
tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/prost-0.8" }
tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/prost-0.8" }
tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/prost-0.8" }

# tendermint              = { path = "../tendermint-rs/tendermint" }
# tendermint-rpc          = { path = "../tendermint-rs/rpc" }
# tendermint-proto        = { path = "../tendermint-rs/proto" }
# tendermint-light-client = { path = "../tendermint-rs/light-client" }
# tendermint-testgen      = { path = "../tendermint-rs/testgen" }
